//EXCEPTIONS
export const GET_EXCEPTIONS = 'GET_EXCEPTIONS';
export const IS_FETCHING_EXCEPTIONS = 'IS_FETCHING_EXCEPTIONS';
export const HAS_STOPPED_FETCHING_EXCEPTIONS = 'HAS_STOPPED_FETCHING_EXCEPTIONS';
export const SELECT_EXCEPTION = 'SELECT_EXCEPTION';
export const CLOSE_EXCEPTION_MODAL = 'CLOSE_EXCEPTION_MODAL';

//ALBUMS
export const GET_ALBUMS = 'GET_ALBUMS';
export const SELECT_ALBUM = 'SELECT_ALBUM';
export const IS_FETCHING_ALBUMS = 'IS_FETCHING_ALBUMS';
export const HAS_STOPPED_FETCHING_ALBUMS = 'HAS_STOPPED_FETCHING_ALBUMS';

//ALBUM BY ID
export const GET_ALBUM_BY_ID = 'GET_ALBUM_BY_ID';
export const IS_FETCHING_ALBUM_BY_ID = 'IS_FETCHING_ALBUM_BY_ID';

// SONGS
export const GET_SONGS = 'GET_SONGS';
export const GET_SONG_BY_ID = 'GET_SONG_BY_ID';
export const GET_ALL_MUSICIANS_ON_SONG = 'GET_ALL_MUSICIANS_ON_SONG';
export const GET_MEDIA = 'GET_MEDIA';
export const IS_FETCHING_SONGS = 'IS_FETCHING_SONGS';
export const HAS_STOPPED_FETCHING_SONGS = 'HAS_STOPPED_FETCHING_SONGS';
export const IS_FETCHING_MUSICIANS = 'IS_FETCHING_MUSICIANS';
export const HAS_STOPPED_FETCHING_MUSICIANS = 'HAS_STOPPED_FETCHING_MUSICIANS';
export const CLEAR_SONGS = 'CLEAR_SONGS';
export const CLEAR_MEDIA = 'CLEAR_MEDIA';
export const CLEAR_SONG_SELECTION = 'CLEAR_SONG_SELECTION';
export const CLEAR_MUSICIANS_ON_SONG = 'CLEAR_MUSICIANS_ON_SONG';
export const ADD_MUSICIAN_TO_SONG = 'ADD_MUSICIAN_TO_SONG';
export const UPDATE_SONG_BY_ID = 'UPDATE_SONG_BY_ID';
export const UPDATE_MUSICIAN_INFO = 'UPDATE_MUSICIAN_INFO';

//SONGS ON ALBUM
export const GET_SONGS_BY_ALBUM_ID = 'GET_SONGS_BY_ALBUM_ID';
export const IS_FETCHING_SONGS_BY_ALBUM_ID = 'IS_FETCHING_SONGS_BY_ALBUM_ID';

export const IS_UPDATING_DATA = 'IS_UPDATING_DATA';
export const HAS_STOPPED_UPDATING_DATA = 'HAS_STOPPED_UPDATING_DATA';
export const UPDATE_DATA = 'UPDATE_SUCCESS';
export const CLEAR_CURRENT_ALBUM = 'CLEAR_CURRENT_ALBUM';

// CACHE
export const SAVE_GROUP_TO_COOKIE = 'SAVE_GROUP_TO_COOKIE';
export const DELETE_GROUP_FROM_COOKIE = 'DELETE_GROUP_FROM_COOKIE';

// PERSON
export const GET_PERSON_BY_ID = 'GET_PERSON_BY_ID';
export const GET_PERSONS_BY_CRITERIA = 'GET_PERSONS_BY_CRITERIA';
export const GET_PERSONS_ROLES = 'GET_PERSONS_ROLES';
export const UPDATE_PERSON_BY_ID = 'UPDATE_PERSON_BY_ID';
export const CLEAR_SELECTED_PERSON = 'CLEAR_SELECTED_PERSON';
export const IS_FETCHING_PERSON = 'IS_FETCHING_PERSON';
export const HAS_STOPPED_FETCHING_PERSON = 'HAS_STOPPED_FETCHING_PERSON';
export const IS_FETCHING_PERSON_MEDIA = 'IS_FETCHING_PERSON_MEDIA';
export const HAS_STOPPED_FETCHING_PERSON_MEDIA = 'HAS_STOPPED_FETCHING_PERSON_MEDIA';
export const IS_FETCHING_PERSON_ALBUMS = 'IS_FETCHING_PERSON_ALBUMS';
export const HAS_STOPPED_FETCHING_PERSON_ALBUMS = 'HAS_STOPPED_FETCHING_PERSON_ALBUMS';
export const GET_MEDIA_ASSOCIATED_WITH_PERSON = 'GET_MEDIA_ASSOCIATED_WITH_PERSON';
export const GET_ALBUMS_ASSOCIATED_WITH_PERSON = 'GET_ALBUMS_ASSOCIATED_WITH_PERSON';
export const REDIRECT_TO_PATH = 'REDIRECT_TO_PATH';