export const GET_EXCEPTIONS = 'GET_EXCEPTIONS';
export const IS_FETCHING_EXCEPTIONS = 'IS_FETCHING_EXCEPTIONS';
export const HAS_STOPPED_FETCHING_EXCEPTIONS = 'HAS_STOPPED_FETCHING_EXCEPTIONS';
export const SELECT_EXCEPTION = 'SELECT_EXCEPTION';
