//EXCEPTIONS
export const GET_EXCEPTIONS = 'GET_EXCEPTIONS';
export const IS_FETCHING_EXCEPTIONS = 'IS_FETCHING_EXCEPTIONS';
export const HAS_STOPPED_FETCHING_EXCEPTIONS = 'HAS_STOPPED_FETCHING_EXCEPTIONS';
export const SELECT_EXCEPTION = 'SELECT_EXCEPTION';
export const CLOSE_EXCEPTION_MODAL = 'CLOSE_EXCEPTION_MODAL';


//ALBUMS
export const GET_ALBUMS = 'GET_ALBUMS';
export const SELECT_ALBUM = 'SELECT_ALBUM';
export const IS_FETCHING_ALBUMS = 'IS_FETCHING_ALBUMS';
export const HAS_STOPPED_FETCHING_ALBUMS = 'HAS_STOPPED_FETCHING_ALBUMS';

// SONGS
export const GET_SONGS = 'GET_SONGS';
export const IS_FETCHING_SONGS = 'IS_FETCHING_SONGS';
export const HAS_STOPPED_FETCHING_SONGS = 'HAS_STOPPED_FETCHING_SONGS';
export const CLEAR_SONGS = 'CLEAR_SONGS';