//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class common_cache_airplayreport
    {
        public int id { get; set; }
        public string station { get; set; }
        public string mucssno { get; set; }
        public string mucname { get; set; }
        public double percinrecording { get; set; }
        public double totalperc { get; set; }
        public double stationperc { get; set; }
        public double playseconds { get; set; }
        public double amount { get; set; }
        public int year { get; set; }
        public string username { get; set; }
        public string recordingtitle { get; set; }
        public string isrc { get; set; }
    }
}
