//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class common_airplay_attributes
    {
        public int year { get; set; }
        public decimal Ras1Ras2 { get; set; }
        public decimal Bylgjan { get; set; }
        public decimal GullOgXid { get; set; }
        public decimal Lettbylgjan { get; set; }
        public decimal FM957 { get; set; }
        public decimal K100 { get; set; }
        public decimal AmountIssued { get; set; }
    }
}
