//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class common_cache_recordingparty_detail
    {
        public int id { get; set; }
        public int groupid { get; set; }
        public Nullable<int> partyartistgroupid { get; set; }
        public int partyrealid { get; set; }
        public string rolecode { get; set; }
        public string instrumentcode { get; set; }
        public Nullable<int> artistpseudonymid { get; set; }
    
        public virtual common_cache_recordingparty common_cache_recordingparty { get; set; }
        public virtual party_mainartist party_mainartist { get; set; }
        public virtual party_instrumenttype party_instrumenttype { get; set; }
        public virtual party_partyroletype party_partyroletype { get; set; }
        public virtual party_pseudonym party_pseudonym { get; set; }
        public virtual party_real party_real { get; set; }
    }
}
