//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class common_cache_mediarecording_detail
    {
        public int id { get; set; }
        public int groupid { get; set; }
        public int recordingid { get; set; }
    
        public virtual common_cache_mediarecording common_cache_mediarecording { get; set; }
        public virtual media_recording media_recording { get; set; }
    }
}
