//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class common_language
    {
        public int LanguageId { get; set; }
        public string Name { get; set; }
        public string LanguageCulture { get; set; }
        public bool Published { get; set; }
        public int DisplayOrder { get; set; }
    }
}
