//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Difference
    {
        public int id { get; set; }
        public Nullable<short> MSdifftool_ErrorCode { get; set; }
        public string MSdifftool_ErrorDescription { get; set; }
    }
}
