//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HljodritEntities : DbContext
    {
        public HljodritEntities()
            : base("name=HljodritEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<common_airplay_attributes> common_airplay_attributes { get; set; }
        public virtual DbSet<common_cache_airplayreport> common_cache_airplayreport { get; set; }
        public virtual DbSet<common_cache_mediarecording> common_cache_mediarecording { get; set; }
        public virtual DbSet<common_cache_mediarecording_detail> common_cache_mediarecording_detail { get; set; }
        public virtual DbSet<common_cache_profile> common_cache_profile { get; set; }
        public virtual DbSet<common_cache_recordingparty> common_cache_recordingparty { get; set; }
        public virtual DbSet<common_cache_recordingparty_detail> common_cache_recordingparty_detail { get; set; }
        public virtual DbSet<common_country> common_country { get; set; }
        public virtual DbSet<common_language> common_language { get; set; }
        public virtual DbSet<common_trackcache> common_trackcache { get; set; }
        public virtual DbSet<common_workbatch> common_workbatch { get; set; }
        public virtual DbSet<common_zipcodes> common_zipcodes { get; set; }
        public virtual DbSet<import_parties> import_parties { get; set; }
        public virtual DbSet<import_tracks> import_tracks { get; set; }
        public virtual DbSet<media_airplay> media_airplay { get; set; }
        public virtual DbSet<media_alternatetitle> media_alternatetitle { get; set; }
        public virtual DbSet<media_formattype> media_formattype { get; set; }
        public virtual DbSet<media_genre> media_genre { get; set; }
        public virtual DbSet<media_product> media_product { get; set; }
        public virtual DbSet<media_product_package> media_product_package { get; set; }
        public virtual DbSet<media_producttype> media_producttype { get; set; }
        public virtual DbSet<media_recording> media_recording { get; set; }
        public virtual DbSet<media_source> media_source { get; set; }
        public virtual DbSet<media_status> media_status { get; set; }
        public virtual DbSet<media_work> media_work { get; set; }
        public virtual DbSet<organization_cataloguerights> organization_cataloguerights { get; set; }
        public virtual DbSet<organization_isrc_series> organization_isrc_series { get; set; }
        public virtual DbSet<organization_labels> organization_labels { get; set; }
        public virtual DbSet<organization_master> organization_master { get; set; }
        public virtual DbSet<organization_type> organization_type { get; set; }
        public virtual DbSet<party_address> party_address { get; set; }
        public virtual DbSet<party_artisttype> party_artisttype { get; set; }
        public virtual DbSet<party_contactmedium> party_contactmedium { get; set; }
        public virtual DbSet<party_groupmembership> party_groupmembership { get; set; }
        public virtual DbSet<party_instrumenttype> party_instrumenttype { get; set; }
        public virtual DbSet<party_mainartist> party_mainartist { get; set; }
        public virtual DbSet<party_partyroletype> party_partyroletype { get; set; }
        public virtual DbSet<party_pseudonym> party_pseudonym { get; set; }
        public virtual DbSet<party_real> party_real { get; set; }
        public virtual DbSet<project_master> project_master { get; set; }
        public virtual DbSet<project_status> project_status { get; set; }
        public virtual DbSet<project_superuser> project_superuser { get; set; }
        public virtual DbSet<project_superuser_organizations> project_superuser_organizations { get; set; }
        public virtual DbSet<project_track> project_track { get; set; }
        public virtual DbSet<project_track_artist> project_track_artist { get; set; }
        public virtual DbSet<project_user> project_user { get; set; }
        public virtual DbSet<recording_party> recording_party { get; set; }
        public virtual DbSet<revenue_activerate> revenue_activerate { get; set; }
        public virtual DbSet<revenue_plan> revenue_plan { get; set; }
        public virtual DbSet<revenue_releaseusage> revenue_releaseusage { get; set; }
        public virtual DbSet<Difference> Difference { get; set; }
        public virtual DbSet<organization_cataloguerights_backup> organization_cataloguerights_backup { get; set; }
        public virtual DbSet<organization_isrc_series_oli> organization_isrc_series_oli { get; set; }
        public virtual DbSet<organization_label_backup> organization_label_backup { get; set; }
        public virtual DbSet<organization_master_backup> organization_master_backup { get; set; }
        public virtual DbSet<organization_master_oli> organization_master_oli { get; set; }
    }
}
