//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_tracks
    {
        public int albumid { get; set; }
        public int done { get; set; }
        public string albumauthor { get; set; }
        public string mainartist { get; set; }
        public string trackname { get; set; }
        public string albumname { get; set; }
        public string labelname { get; set; }
        public string catalogue { get; set; }
        public string isrc { get; set; }
        public int trackid { get; set; }
        public Nullable<int> releaseyear { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<int> ras1 { get; set; }
        public Nullable<int> ras2 { get; set; }
        public Nullable<int> gullfm { get; set; }
        public Nullable<int> lettfm { get; set; }
        public Nullable<int> xfm { get; set; }
        public Nullable<int> fm957 { get; set; }
        public Nullable<int> bylgjan { get; set; }
        public Nullable<int> person1 { get; set; }
        public Nullable<int> person2 { get; set; }
        public Nullable<int> person3 { get; set; }
        public Nullable<int> person4 { get; set; }
        public Nullable<int> person5 { get; set; }
        public Nullable<int> person6 { get; set; }
        public Nullable<int> person7 { get; set; }
        public Nullable<int> person8 { get; set; }
        public Nullable<int> person9 { get; set; }
        public Nullable<int> person10 { get; set; }
        public Nullable<int> person11 { get; set; }
        public Nullable<int> person12 { get; set; }
        public Nullable<int> person13 { get; set; }
        public Nullable<int> person14 { get; set; }
        public Nullable<int> person15 { get; set; }
        public Nullable<int> person16 { get; set; }
        public Nullable<int> person17 { get; set; }
        public Nullable<int> role1 { get; set; }
        public Nullable<int> role2 { get; set; }
        public Nullable<int> role3 { get; set; }
        public Nullable<int> role4 { get; set; }
        public Nullable<int> role5 { get; set; }
        public Nullable<int> role6 { get; set; }
        public Nullable<int> role7 { get; set; }
        public Nullable<int> role8 { get; set; }
        public Nullable<int> role9 { get; set; }
        public Nullable<int> role10 { get; set; }
        public Nullable<int> role11 { get; set; }
        public Nullable<int> role12 { get; set; }
        public Nullable<int> role13 { get; set; }
        public Nullable<int> role14 { get; set; }
        public Nullable<int> role15 { get; set; }
        public Nullable<int> role16 { get; set; }
        public Nullable<int> role17 { get; set; }
        public Nullable<int> musicrole1_1 { get; set; }
        public Nullable<int> musicrole1_2 { get; set; }
        public Nullable<int> musicrole1_3 { get; set; }
        public Nullable<int> musicrole1_4 { get; set; }
        public Nullable<int> musicrole1_5 { get; set; }
        public Nullable<int> musicrole2_1 { get; set; }
        public Nullable<int> musicrole2_2 { get; set; }
        public Nullable<int> musicrole2_3 { get; set; }
        public Nullable<int> musicrole2_4 { get; set; }
        public Nullable<int> musicrole2_5 { get; set; }
        public Nullable<int> musicrole3_1 { get; set; }
        public Nullable<int> musicrole3_2 { get; set; }
        public Nullable<int> musicrole3_3 { get; set; }
        public Nullable<int> musicrole3_4 { get; set; }
        public Nullable<int> musicrole3_5 { get; set; }
        public Nullable<int> musicrole4_1 { get; set; }
        public Nullable<int> musicrole4_2 { get; set; }
        public Nullable<int> musicrole4_3 { get; set; }
        public Nullable<int> musicrole4_4 { get; set; }
        public Nullable<int> musicrole4_5 { get; set; }
        public Nullable<int> musicrole5_1 { get; set; }
        public Nullable<int> musicrole5_2 { get; set; }
        public Nullable<int> musicrole5_3 { get; set; }
        public Nullable<int> musicrole5_4 { get; set; }
        public Nullable<int> musicrole5_5 { get; set; }
        public Nullable<int> musicrole6_1 { get; set; }
        public Nullable<int> musicrole6_2 { get; set; }
        public Nullable<int> musicrole6_3 { get; set; }
        public Nullable<int> musicrole6_4 { get; set; }
        public Nullable<int> musicrole6_5 { get; set; }
        public Nullable<int> musicrole7_1 { get; set; }
        public Nullable<int> musicrole7_2 { get; set; }
        public Nullable<int> musicrole7_3 { get; set; }
        public Nullable<int> musicrole7_4 { get; set; }
        public Nullable<int> musicrole7_5 { get; set; }
        public Nullable<int> musicrole8_1 { get; set; }
        public Nullable<int> musicrole8_2 { get; set; }
        public Nullable<int> musicrole8_3 { get; set; }
        public Nullable<int> musicrole8_4 { get; set; }
        public Nullable<int> musicrole8_5 { get; set; }
        public Nullable<int> musicrole9_1 { get; set; }
        public Nullable<int> musicrole9_2 { get; set; }
        public Nullable<int> musicrole9_3 { get; set; }
        public Nullable<int> musicrole9_4 { get; set; }
        public Nullable<int> musicrole9_5 { get; set; }
        public Nullable<int> musicrole10_1 { get; set; }
        public Nullable<int> musicrole10_2 { get; set; }
        public Nullable<int> musicrole10_3 { get; set; }
        public Nullable<int> musicrole10_4 { get; set; }
        public Nullable<int> musicrole10_5 { get; set; }
        public Nullable<int> musicrole11_1 { get; set; }
        public Nullable<int> musicrole11_2 { get; set; }
        public Nullable<int> musicrole11_3 { get; set; }
        public Nullable<int> musicrole11_4 { get; set; }
        public Nullable<int> musicrole11_5 { get; set; }
        public Nullable<int> musicrole12_1 { get; set; }
        public Nullable<int> musicrole12_2 { get; set; }
        public Nullable<int> musicrole12_3 { get; set; }
        public Nullable<int> musicrole12_4 { get; set; }
        public Nullable<int> musicrole12_5 { get; set; }
        public Nullable<int> musicrole13_1 { get; set; }
        public Nullable<int> musicrole13_2 { get; set; }
        public Nullable<int> musicrole13_3 { get; set; }
        public Nullable<int> musicrole13_4 { get; set; }
        public Nullable<int> musicrole13_5 { get; set; }
        public Nullable<int> musicrole14_1 { get; set; }
        public Nullable<int> musicrole14_2 { get; set; }
        public Nullable<int> musicrole14_3 { get; set; }
        public Nullable<int> musicrole14_4 { get; set; }
        public Nullable<int> musicrole14_5 { get; set; }
        public Nullable<int> musicrole15_1 { get; set; }
        public Nullable<int> musicrole15_2 { get; set; }
        public Nullable<int> musicrole15_3 { get; set; }
        public Nullable<int> musicrole15_4 { get; set; }
        public Nullable<int> musicrole15_5 { get; set; }
        public Nullable<int> musicrole16_1 { get; set; }
        public Nullable<int> musicrole16_2 { get; set; }
        public Nullable<int> musicrole16_3 { get; set; }
        public Nullable<int> musicrole16_4 { get; set; }
        public Nullable<int> musicrole16_5 { get; set; }
        public Nullable<int> musicrole17_1 { get; set; }
        public Nullable<int> musicrole17_2 { get; set; }
        public Nullable<int> musicrole17_3 { get; set; }
        public Nullable<int> musicrole17_4 { get; set; }
        public Nullable<int> musicrole17_5 { get; set; }
    }
}
