//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class media_source
    {
        public int id { get; set; }
        public string isrc { get; set; }
        public int recordingid { get; set; }
        public string formattypeid { get; set; }
        public Nullable<int> sourcebitrate { get; set; }
        public Nullable<decimal> sourcesizeinkb { get; set; }
        public Nullable<System.TimeSpan> duration { get; set; }
        public string sourcelocation { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedon { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdon { get; set; }
    
        public virtual media_formattype media_formattype { get; set; }
        public virtual media_recording media_recording { get; set; }
    }
}
