//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class media_airplay
    {
        public int id { get; set; }
        public int mediaproductid { get; set; }
        public int year { get; set; }
        public Nullable<int> bylgjan { get; set; }
        public Nullable<int> lettbylgjan { get; set; }
        public Nullable<int> fm957 { get; set; }
        public Nullable<int> xid977 { get; set; }
        public Nullable<int> gull { get; set; }
        public Nullable<int> k100 { get; set; }
        public Nullable<int> ras1 { get; set; }
        public Nullable<int> ras2 { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedon { get; set; }
    
        public virtual media_product media_product { get; set; }
    }
}
