//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class media_product_package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public media_product_package()
        {
            this.media_product = new HashSet<media_product>();
        }
    
        public int id { get; set; }
        public Nullable<int> albumid { get; set; }
        public string albumtitle { get; set; }
        public Nullable<int> labelid { get; set; }
        public string cataloguenumber { get; set; }
        public string releasetypecode { get; set; }
        public string physicallocation { get; set; }
        public Nullable<int> countryofproduction { get; set; }
        public Nullable<int> countryofpublication { get; set; }
        public DateTime releasedate { get; set; }
        public Nullable<int> packagestatusid { get; set; }
        public Nullable<int> numberoftracks { get; set; }
        public Nullable<int> formattypeid { get; set; }
        public string issnserialnumber { get; set; }
        public string comment { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedon { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdon { get; set; }
        public Nullable<int> mainartistid { get; set; }
    
        public virtual common_country common_country { get; set; }
        public virtual common_country common_country1 { get; set; }
        public virtual media_formattype media_formattype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<media_product> media_product { get; set; }
        public virtual organization_labels organization_labels { get; set; }
        public virtual party_mainartist party_mainartist { get; set; }
        public virtual media_producttype media_producttype { get; set; }
        public virtual media_status media_status { get; set; }
    }
}
