//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class organization_master_backup
    {
        public int id { get; set; }
        public string uniqueidentifier { get; set; }
        public string name { get; set; }
        public int organizationtype { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string zipcode { get; set; }
        public Nullable<int> countrycode { get; set; }
        public string telephone { get; set; }
        public string maincontact { get; set; }
        public string maincontactemail { get; set; }
        public string maincontacttel { get; set; }
        public string website { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedon { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdon { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
