//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class organization_labels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public organization_labels()
        {
            this.media_product_package = new HashSet<media_product_package>();
            this.organization_cataloguerights = new HashSet<organization_cataloguerights>();
        }
    
        public int id { get; set; }
        public int organizationid { get; set; }
        public string labelname { get; set; }
        public Nullable<int> countrycode { get; set; }
        public Nullable<System.DateTime> dateissued { get; set; }
        public bool rights_world { get; set; }
        public bool rights_ownterritory { get; set; }
        public bool rights_europe { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedon { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<media_product_package> media_product_package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<organization_cataloguerights> organization_cataloguerights { get; set; }
        public virtual organization_master organization_master { get; set; }
    }
}
