//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class organization_label_backup
    {
        public int id { get; set; }
        public int organizationid { get; set; }
        public string labelname { get; set; }
        public Nullable<int> countrycode { get; set; }
        public Nullable<System.DateTime> dateissued { get; set; }
        public bool rights_world { get; set; }
        public bool rights_ownterritory { get; set; }
        public bool rights_europe { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedon { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdon { get; set; }
    }
}
