//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class party_contactmedium
    {
        public int partyrealid { get; set; }
        public string uniqueidentifier { get; set; }
        public string homephone { get; set; }
        public string workphone { get; set; }
        public string mobilephone { get; set; }
        public string fax { get; set; }
        public string emailaddress { get; set; }
        public string skypeid { get; set; }
        public string msnid { get; set; }
        public Nullable<int> preferredmedium { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedon { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdon { get; set; }
    
        public virtual party_real party_real { get; set; }
    }
}
