//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class party_mainartist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public party_mainartist()
        {
            this.common_cache_recordingparty_detail = new HashSet<common_cache_recordingparty_detail>();
            this.media_product_package = new HashSet<media_product_package>();
            this.media_recording = new HashSet<media_recording>();
            this.party_groupmembership = new HashSet<party_groupmembership>();
            this.project_master = new HashSet<project_master>();
        }
    
        public int id { get; set; }
        public string artistname { get; set; }
        public Nullable<int> partyrealid { get; set; }
        public string artisttypecode { get; set; }
        public string peformancetype { get; set; }
        public string genre { get; set; }
        public Nullable<int> maincontactid { get; set; }
        public string website { get; set; }
        public string imagepath { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<int> artistnationalitycode { get; set; }
        public string details { get; set; }
        public string externalid { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedon { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdon { get; set; }
        public string stefnumber { get; set; }
        public Nullable<int> groupsize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<common_cache_recordingparty_detail> common_cache_recordingparty_detail { get; set; }
        public virtual common_country common_country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<media_product_package> media_product_package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<media_recording> media_recording { get; set; }
        public virtual party_artisttype party_artisttype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<party_groupmembership> party_groupmembership { get; set; }
        public virtual party_real party_real { get; set; }
        public virtual party_real party_real1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_master> project_master { get; set; }
    }
}
