//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class party_address
    {
        public int id { get; set; }
        public Nullable<int> partyid { get; set; }
        public string street1 { get; set; }
        public string street2 { get; set; }
        public string postalbox { get; set; }
        public string floor { get; set; }
        public Nullable<int> zipcode { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string countrycode { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedon { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdon { get; set; }
    }
}
