//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class party_artistdefaultroles
    {
        public int id { get; set; }
        public int mainartistid { get; set; }
        public string rolecode { get; set; }
        public Nullable<int> sortorder { get; set; }
        public string comment { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedon { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdon { get; set; }
    
        public virtual party_mainartist party_mainartist { get; set; }
        public virtual party_partyroletype party_partyroletype { get; set; }
    }
}
