//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_track
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project_track()
        {
            this.project_track_artist = new HashSet<project_track_artist>();
        }
    
        public int id { get; set; }
        public int projectid { get; set; }
        public string trackname { get; set; }
        public bool isworkingtitle { get; set; }
        public string comment { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedon { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdon { get; set; }
        public string isrc { get; set; }
        public Nullable<System.TimeSpan> duration { get; set; }
        public Nullable<int> authorexceptioncode { get; set; }
        public bool donotpublish { get; set; }
        public int trackorder { get; set; }
        public Nullable<int> recordingid { get; set; }
    
        public virtual project_master project_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_track_artist> project_track_artist { get; set; }
    }
}
