//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project_master()
        {
            this.project_track = new HashSet<project_track>();
            this.project_user = new HashSet<project_user>();
        }
    
        public int id { get; set; }
        public string projectname { get; set; }
        public Nullable<int> mainmanagerid { get; set; }
        public System.DateTime projectstartdate { get; set; }
        public Nullable<System.DateTime> projectenddate { get; set; }
        public bool isworkingtitle { get; set; }
        public string comment { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedon { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdon { get; set; }
        public string statuscode { get; set; }
        public bool removed { get; set; }
        public string reviewedby { get; set; }
        public Nullable<System.DateTime> reviewedon { get; set; }
        public string reviewedcomment { get; set; }
        public Nullable<bool> reviewedok { get; set; }
        public Nullable<int> organizationid { get; set; }
        public string mainartist { get; set; }
        public Nullable<int> mainartistid { get; set; }
    
        public virtual organization_master organization_master { get; set; }
        public virtual party_mainartist party_mainartist { get; set; }
        public virtual party_real party_real { get; set; }
        public virtual project_status project_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_track> project_track { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_user> project_user { get; set; }
    }
}
