//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_user
    {
        public int id { get; set; }
        public int projectid { get; set; }
        public string email { get; set; }
        public string fullname { get; set; }
        public System.Guid guid { get; set; }
        public bool admin { get; set; }
        public string username { get; set; }
        public bool activated { get; set; }
        public string invitedbyuser { get; set; }
    
        public virtual project_master project_master { get; set; }
    }
}
