//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_track_artist
    {
        public int id { get; set; }
        public int projecttrackid { get; set; }
        public int partyrealid { get; set; }
        public string rolecode { get; set; }
        public string instrumentcode { get; set; }
        public Nullable<int> artistpseudonymid { get; set; }
        public string comment { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedon { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdon { get; set; }
    
        public virtual party_instrumenttype party_instrumenttype { get; set; }
        public virtual party_partyroletype party_partyroletype { get; set; }
        public virtual party_pseudonym party_pseudonym { get; set; }
        public virtual party_real party_real { get; set; }
        public virtual project_track project_track { get; set; }
    }
}
