//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_superuser_organizations
    {
        public int id { get; set; }
        public string username { get; set; }
        public int organizationid { get; set; }
    
        public virtual organization_master organization_master { get; set; }
        public virtual project_superuser project_superuser { get; set; }
    }
}
