//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class revenue_releaseusage
    {
        public int id { get; set; }
        public string customeridentifier { get; set; }
        public string customersubidentifier { get; set; }
        public string isrc { get; set; }
        public string title { get; set; }
        public string parenttitle { get; set; }
        public string mainartistname { get; set; }
        public Nullable<System.DateTime> releasedate { get; set; }
        public System.DateTime playstarttime { get; set; }
        public System.DateTime playendtime { get; set; }
        public Nullable<System.TimeSpan> duration { get; set; }
        public Nullable<bool> isrefundtransaction { get; set; }
        public Nullable<bool> trackmatchfound { get; set; }
        public Nullable<System.DateTime> dateofcharge { get; set; }
        public Nullable<bool> isdisputed { get; set; }
        public string comment { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedon { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdon { get; set; }
        public string trackid { get; set; }
    }
}
