//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFH.IT.Hljodrit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class revenue_activerate
    {
        public int id { get; set; }
        public int revenueplanid { get; set; }
        public decimal revenueperunit { get; set; }
        public Nullable<decimal> vat { get; set; }
        public System.DateTime validfrom { get; set; }
        public Nullable<System.DateTime> validuntil { get; set; }
        public string updatedby { get; set; }
        public System.DateTime updatedon { get; set; }
        public string createdby { get; set; }
        public System.DateTime createdon { get; set; }
    
        public virtual revenue_plan revenue_plan { get; set; }
    }
}
