CREATE TABLE [dbo].[import_tracks] (
    [albumid]       INT            NOT NULL,
    [done]          INT            NOT NULL,
    [albumauthor]   NVARCHAR (300) NULL,
    [mainartist]    NVARCHAR (300) NULL,
    [trackname]     NVARCHAR (500) NOT NULL,
    [albumname]     NVARCHAR (300) NULL,
    [labelname]     NVARCHAR (200) NULL,
    [catalogue]     NVARCHAR (30)  NULL,
    [isrc]          NVARCHAR (15)  NULL,
    [trackid]       INT            NOT NULL,
    [releaseyear]   INT            NULL,
    [duration]      INT            NULL,
    [ras1]          INT            NULL,
    [ras2]          INT            NULL,
    [gullfm]        INT            NULL,
    [lettfm]        INT            NULL,
    [xfm]           INT            NULL,
    [fm957]         INT            NULL,
    [bylgjan]       INT            NULL,
    [person1]       INT            NULL,
    [person2]       INT            NULL,
    [person3]       INT            NULL,
    [person4]       INT            NULL,
    [person5]       INT            NULL,
    [person6]       INT            NULL,
    [person7]       INT            NULL,
    [person8]       INT            NULL,
    [person9]       INT            NULL,
    [person10]      INT            NULL,
    [person11]      INT            NULL,
    [person12]      INT            NULL,
    [person13]      INT            NULL,
    [person14]      INT            NULL,
    [person15]      INT            NULL,
    [person16]      INT            NULL,
    [person17]      INT            NULL,
    [role1]         INT            NULL,
    [role2]         INT            NULL,
    [role3]         INT            NULL,
    [role4]         INT            NULL,
    [role5]         INT            NULL,
    [role6]         INT            NULL,
    [role7]         INT            NULL,
    [role8]         INT            NULL,
    [role9]         INT            NULL,
    [role10]        INT            NULL,
    [role11]        INT            NULL,
    [role12]        INT            NULL,
    [role13]        INT            NULL,
    [role14]        INT            NULL,
    [role15]        INT            NULL,
    [role16]        INT            NULL,
    [role17]        INT            NULL,
    [musicrole1-1]  INT            NULL,
    [musicrole1-2]  INT            NULL,
    [musicrole1-3]  INT            NULL,
    [musicrole1-4]  INT            NULL,
    [musicrole1-5]  INT            NULL,
    [musicrole2-1]  INT            NULL,
    [musicrole2-2]  INT            NULL,
    [musicrole2-3]  INT            NULL,
    [musicrole2-4]  INT            NULL,
    [musicrole2-5]  INT            NULL,
    [musicrole3-1]  INT            NULL,
    [musicrole3-2]  INT            NULL,
    [musicrole3-3]  INT            NULL,
    [musicrole3-4]  INT            NULL,
    [musicrole3-5]  INT            NULL,
    [musicrole4-1]  INT            NULL,
    [musicrole4-2]  INT            NULL,
    [musicrole4-3]  INT            NULL,
    [musicrole4-4]  INT            NULL,
    [musicrole4-5]  INT            NULL,
    [musicrole5-1]  INT            NULL,
    [musicrole5-2]  INT            NULL,
    [musicrole5-3]  INT            NULL,
    [musicrole5-4]  INT            NULL,
    [musicrole5-5]  INT            NULL,
    [musicrole6-1]  INT            NULL,
    [musicrole6-2]  INT            NULL,
    [musicrole6-3]  INT            NULL,
    [musicrole6-4]  INT            NULL,
    [musicrole6-5]  INT            NULL,
    [musicrole7-1]  INT            NULL,
    [musicrole7-2]  INT            NULL,
    [musicrole7-3]  INT            NULL,
    [musicrole7-4]  INT            NULL,
    [musicrole7-5]  INT            NULL,
    [musicrole8-1]  INT            NULL,
    [musicrole8-2]  INT            NULL,
    [musicrole8-3]  INT            NULL,
    [musicrole8-4]  INT            NULL,
    [musicrole8-5]  INT            NULL,
    [musicrole9-1]  INT            NULL,
    [musicrole9-2]  INT            NULL,
    [musicrole9-3]  INT            NULL,
    [musicrole9-4]  INT            NULL,
    [musicrole9-5]  INT            NULL,
    [musicrole10-1] INT            NULL,
    [musicrole10-2] INT            NULL,
    [musicrole10-3] INT            NULL,
    [musicrole10-4] INT            NULL,
    [musicrole10-5] INT            NULL,
    [musicrole11-1] INT            NULL,
    [musicrole11-2] INT            NULL,
    [musicrole11-3] INT            NULL,
    [musicrole11-4] INT            NULL,
    [musicrole11-5] INT            NULL,
    [musicrole12-1] INT            NULL,
    [musicrole12-2] INT            NULL,
    [musicrole12-3] INT            NULL,
    [musicrole12-4] INT            NULL,
    [musicrole12-5] INT            NULL,
    [musicrole13-1] INT            NULL,
    [musicrole13-2] INT            NULL,
    [musicrole13-3] INT            NULL,
    [musicrole13-4] INT            NULL,
    [musicrole13-5] INT            NULL,
    [musicrole14-1] INT            NULL,
    [musicrole14-2] INT            NULL,
    [musicrole14-3] INT            NULL,
    [musicrole14-4] INT            NULL,
    [musicrole14-5] INT            NULL,
    [musicrole15-1] INT            NULL,
    [musicrole15-2] INT            NULL,
    [musicrole15-3] INT            NULL,
    [musicrole15-4] INT            NULL,
    [musicrole15-5] INT            NULL,
    [musicrole16-1] INT            NULL,
    [musicrole16-2] INT            NULL,
    [musicrole16-3] INT            NULL,
    [musicrole16-4] INT            NULL,
    [musicrole16-5] INT            NULL,
    [musicrole17-1] INT            NULL,
    [musicrole17-2] INT            NULL,
    [musicrole17-3] INT            NULL,
    [musicrole17-4] INT            NULL,
    [musicrole17-5] INT            NULL,
    CONSTRAINT [PK_import_tracks] PRIMARY KEY CLUSTERED ([trackid] ASC)
);

