CREATE TABLE [dbo].[revenue_releaseusage] (
    [id]                    INT            IDENTITY (1, 1) NOT NULL,
    [customeridentifier]    NVARCHAR (30)  NOT NULL,
    [customersubidentifier] NVARCHAR (30)  NULL,
    [isrc]                  NVARCHAR (20)  NULL,
    [title]                 NVARCHAR (200) NULL,
    [parenttitle]           NVARCHAR (200) NULL,
    [mainartistname]        NVARCHAR (200) NULL,
    [releasedate]           DATETIME       NULL,
    [playstarttime]         DATETIME       NOT NULL,
    [playendtime]           DATETIME       NOT NULL,
    [duration]              TIME (7)       NULL,
    [isrefundtransaction]   BIT            NULL,
    [trackmatchfound]       BIT            NULL,
    [dateofcharge]          DATETIME       NULL,
    [isdisputed]            BIT            NULL,
    [comment]               NVARCHAR (500) NULL,
    [updatedby]             NVARCHAR (50)  NOT NULL,
    [updatedon]             DATETIME       NOT NULL,
    [createdby]             NVARCHAR (50)  NOT NULL,
    [createdon]             DATETIME       NOT NULL,
    [trackid]               NVARCHAR (30)  NULL,
    CONSTRAINT [PK_recording.usage] PRIMARY KEY CLUSTERED ([id] ASC)
);

