// PROJECT
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const IS_CREATING_PROJECT = 'IS_CREATING_PROJECT';
export const HAS_STOPPED_CREATING_PROJECT = 'HAS_STOPPED_CREATING_PROJECT';
export const UPDATE_PROJECT_BASIC_INFO = 'UPDATE_PROJECT_BASIC_INFO';
export const UPDATE_PROJECT_SONGS = 'UPDATE_PROJECT_SONGS';
export const UPDATE_PROJECT_PERFORMERS = 'UPDATE_PROJECT_PERFORMERS';
export const UPDATE_PROJECT_PRODUCERS = 'UPDATE_PROJECT_PRODUCERS';

// FLOW
export const IS_UPDATING_DATA = 'IS_UPDATING_DATA';
export const HAS_STOPPED_UPDATING_DATA = 'HAS_STOPPED_UPDATING_DATA';
export const UPDATE_DATA = 'UPDATE_DATA';
export const REGISTER_INDIVIDUAL = 'REGISTER_INDIVIDUAL';
export const IS_REGISTERING_INDIVIDUAL = 'IS_REGISTERING_INDIVIDUAL';
export const HAS_STOPPED_REGISTERING_INDIVIDUAL = 'HAS_STOPPED_REGISTERING_INDIVIDUAL';
export const IS_FETCHING_LIST = 'IS_FETCHING_LIST';
export const HAS_STOPPED_FETCHING_LIST = 'HAS_STOPPED_FETCHING_LIST';
export const RESET_REGISTER_ID = 'RESET_REGISTER_ID';

// MEDIA
export const GET_MEDIA = 'GET_MEDIA';
export const IS_FETCHING_SONGS = 'IS_FETCHING_SONGS';
export const HAS_STOPPED_FETCHING_SONGS = 'HAS_STOPPED_FETCHING_SONGS';
export const CLEAR_MEDIA = 'CLEAR_MEDIA';

// PERSON
export const GET_PERSONS_BY_CRITERIA = 'GET_PERSONS_BY_CRITERIA';

// INSTRUMENT
export const GET_INSTRUMENT_SUGGESTIONS = 'GET_INSTRUMENT_SUGGESTIONS';

// PUBLISHER
export const GET_ALL_PUBLISHERS = 'GET_ALL_PUBLISHERS';
export const GET_PUBLISHER_ISRC_SERIES_BY_ID = 'GET_PUBLISHER_ISRC_SERIES_BY_ID';
export const GET_PUBLISHER_LABELS_BY_ID = 'GET_PUBLISHER_LABELS_BY_ID';
export const ADD_LABEL_TO_PUBLISHER_BY_ID = 'ADD_LABEL_TO_PUBLISHER_BY_ID';
export const IS_CREATING_LABEL = 'IS_CREATING_LABEL';
export const HAS_STOPPED_CREATING_LABEL = 'HAS_STOPPED_CREATING_LABEL';