// PROJECT
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const IS_CREATING_PROJECT = 'IS_CREATING_PROJECT';
export const HAS_STOPPED_CREATING_PROJECT = 'HAS_STOPPED_CREATING_PROJECT';
export const UPDATE_PROJECT_BASIC_INFO = 'UPDATE_PROJECT_BASIC_INFO';
export const UPDATE_PROJECT_SONGS = 'UPDATE_PROJECT_SONGS';
export const UPDATE_PROJECT_PERFORMERS = 'UPDATE_PROJECT_PERFORMERS';
export const UPDATE_PROJECT_PRODUCERS = 'UPDATE_PROJECT_PRODUCERS';
export const GET_PROJECT_STATUS = 'GET_PROJECT_STATUS';
export const GET_PROJECT_FOR_USER = 'GET_PROJECT_FOR_USER';
export const IS_FETCHING_USER_PROJECTS = 'IS_FETCHING_USER_PROJECTS';
export const HAS_STOPPED_FETCHING_USER_PROJECTS = 'HAS_STOPPED_FETCHING_USER_PROJECTS';
export const GET_PROJECT_BY_ID = 'GET_PROJECT_BY_ID';
export const IS_FETCHING_PROJECT_BY_ID = 'IS_FETCHING_PROJECT_BY_ID';
export const HAS_STOPPED_FETCHING_PROJECT_BY_ID = 'HAS_STOPPED_FETCHING_PROJECT_BY_ID';
export const UPDATE_PROJECT_BY_ID = 'UPDATE_PROJECT_BY_ID';
export const CLEAR_CURRENT_PROJECT = 'CLEAR_CURRENT_PROJECT';
export const GET_PROJECT_TRACKS_BY_ID = 'GET_PROJECT_TRACKS_BY_ID';

// FLOW
export const IS_UPDATING_DATA = 'IS_UPDATING_DATA';
export const HAS_STOPPED_UPDATING_DATA = 'HAS_STOPPED_UPDATING_DATA';
export const UPDATE_DATA = 'UPDATE_DATA';
export const REGISTER_INDIVIDUAL = 'REGISTER_INDIVIDUAL';
export const IS_REGISTERING_INDIVIDUAL = 'IS_REGISTERING_INDIVIDUAL';
export const HAS_STOPPED_REGISTERING_INDIVIDUAL = 'HAS_STOPPED_REGISTERING_INDIVIDUAL';
export const IS_FETCHING_LIST = 'IS_FETCHING_LIST';
export const HAS_STOPPED_FETCHING_LIST = 'HAS_STOPPED_FETCHING_LIST';
export const RESET_REGISTER_ID = 'RESET_REGISTER_ID';

// MEDIA
export const GET_MEDIA = 'GET_MEDIA';
export const IS_FETCHING_SONGS = 'IS_FETCHING_SONGS';
export const HAS_STOPPED_FETCHING_SONGS = 'HAS_STOPPED_FETCHING_SONGS';
export const CLEAR_MEDIA = 'CLEAR_MEDIA';

// PERSON
export const GET_PERSONS_BY_CRITERIA = 'GET_PERSONS_BY_CRITERIA';
export const GET_PERSONS_ROLES = 'GET_PERSONS_ROLES';

// INSTRUMENT
export const GET_INSTRUMENT_SUGGESTIONS = 'GET_INSTRUMENT_SUGGESTIONS';

// PUBLISHER
export const GET_ALL_PUBLISHERS = 'GET_ALL_PUBLISHERS';
export const GET_PUBLISHER_ISRC_SERIES_BY_ID = 'GET_PUBLISHER_ISRC_SERIES_BY_ID';
export const GET_PUBLISHER_LABELS_BY_ID = 'GET_PUBLISHER_LABELS_BY_ID';
export const ADD_LABEL_TO_PUBLISHER_BY_ID = 'ADD_LABEL_TO_PUBLISHER_BY_ID';
export const IS_CREATING_LABEL = 'IS_CREATING_LABEL';
export const HAS_STOPPED_CREATING_LABEL = 'HAS_STOPPED_CREATING_LABEL';

// CACHE
export const SAVE_GROUP_TO_COOKIE = 'SAVE_GROUP_TO_COOKIE';

// AUTHENTICATION
export const IS_LOGGING_IN = 'IS_LOGGING_IN';
export const HAS_STOPPED_LOGGING_IN = 'HAS_STOPPED_LOGGING_IN';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT = 'LOGOUT';
export const IS_REGISTERING = 'IS_REGISTERING';
export const HAS_STOPPED_REGISTERING = 'HAS_STOPPED_REGISTERING';
export const REFRESH_LOGIN = 'REFRESH_LOGIN';
export const CLEAR_LOGIN = 'CLEAR_LOGIN';