// PROJECT
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const IS_CREATING_PROJECT = 'IS_CREATING_PROJECT';
export const HAS_STOPPED_CREATING_PROJECT = 'HAS_STOPPED_CREATING_PROJECT';

// FLOW
export const IS_UPDATING_DATA = 'IS_UPDATING_DATA';
export const HAS_STOPPED_UPDATING_DATA = 'HAS_STOPPED_UPDATING_DATA';
export const UPDATE_DATA = 'UPDATE_DATA';
export const REGISTER_INDIVIDUAL = 'REGISTER_INDIVIDUAL';
export const IS_REGISTERING_INDIVIDUAL = 'IS_REGISTERING_INDIVIDUAL';
export const HAS_STOPPED_REGISTERING_INDIVIDUAL = 'HAS_STOPPED_REGISTERING_INDIVIDUAL';
export const IS_FETCHING_LIST = 'IS_FETCHING_LIST';
export const HAS_STOPPED_FETCHING_LIST = 'HAS_STOPPED_FETCHING_LIST';
export const RESET_REGISTER_ID = 'RESET_REGISTER_ID';